[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concert-downloader"
version = "0.1.0"
authors = [
  { name="Andres Delgado", email="your-email@example.com" },
]
description = "A tool to download and split concerts from YouTube or local files."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "click>=8.1.0",
    "pydantic>=2.0.0",
    "pytubefix",
    "rich",
    "plyer",
    "ffmpeg",
]

[project.scripts]
concert_downloader = "concert_downloader.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["concert_downloader*"]
